FROM eclipse-temurin:17.0.12_7-jdk-noble

RUN apt-get update && apt-get install --yes \
    git \
    graphviz \
    libxi-dev \
    libxtst6 \
    make \
    nodejs && \
    apt-get clean && apt-get autoremove
